sudo: required
language: node_js
node_js:
- '8'
script:
- npm test
deploy:
  provider: npm
  email: spanners@findmypast.com
  api_key:
    secure: AXddijSjr90hGWgnFAdHECIwpdp5P8AoQgVIHdQ1Y62gU4DgmcZuJxmcCJlET2pi/dB6rseJcyDeMj8s+OqLBhTeK8yzjsNXFVymq6lN/HO5hgEoe8FwimBz9lWiUVNqi43UMpezhddOebNDnVIYTbaEEZFzmYW3+nrpA0TTOCdWa+ny1TK575a/JyIKinwQGMJ8JKbbaX1zq+FEAAkqz/dMkR5rMB1hz+oonhvU/e8FOm79J6Qv8n5l877QSIRI4/6ywJgtt+zwuqnyL4Qmrwfs1fD9qB2SrXuHnY4X2NN3j0YBzXNCufestpzQwq/V7Hm3EeASWrcm0xEPk8RINrAGj48b5NCVyAdufanr2c4cBbudw5p/Rnedj/IJLeKLc4kZx2LbiD74KMhPAQELnPafuz29REU9FT1pjLPNH56vKhqVkvGb1zdzTGVfqzmUPH17cnL55Fx2jmDQhg2PEM11brHc8SXqGYrRT2XDAMZWhtGZtl/TAVusyN1zwgEkcwlK9eNSRITAIioNiQ154ABJORnVSHDIUW7tkim3OJF3e3tev6mP5ehVUrgdqfYuVxtClEEN5NypdL8kPiYz7yaPMfO4zASTycDVzDOh9W7agnNP+HfUKieIUBqVyUMCpLVC0Jezf/YvGchE+12jypLjIp1J6LDJMIbdTFZho28=
  on:
    tags: true
    repo: findmypast-oss/scoosh

notifications:
  slack:
    secure: n8CNXbGl/wtsacVg9+i/hFOq+zGR7oSIaxPoQb2XhkZOwSSTYw4IPjxsnEAGvXLMeVOHgnD1jEPXw1c5cHpOu3sUW5sDEl9EYXaIWU3EfB6rAQkfgF5eOChXBo+MpVeUkVLy1OCpo4/j5qfnoQb9yxZ4sjVGHrFNLdDpriLU9UQZN8W7IZs6C0jWwqWVXwUa2nXMtBEp1Wm93yQcaehfxF06DHuRaSln5CUBFX2UbVIRgxNDjNbXF9UOmlK5yJlYTXtoOXcelKMo399qzu6YsGVjBQq32nWWKoKWvuK/mqR8kZXMkfOeFvUIbhwkperxYioGOw1Fe/XUzG6BSr6si/7DYda4c5jsQwu6+W/rOTDuF56vBnhl20Es6fEsVT+mVCxopk3OkwfQMg4DZiqKlXhvEyXlzHKMgn0bfDg0PbnFwzIYjcz7jZ8Wt4mhHM2v8AyCHXHeVdftw5uQiXR2jvi7swSUmRNgaLHLC9CF/5+sKJD8AO+Dfdlw+ry7BtixglWs03wNYSFUaluoh23lyxRiK0r8E1pzm/9MJN3egS3iPgOAiMTMl2qk6aGLoDJvinXibI+b+IlEBKirnasrKE8RdW8ufrSjcLJoq2JtXd7DItwdMnasUt8nLl6V67XoOqUrGEbXwvw/NAtFuDD8F5u81d/o80qsTFnFPyGnsis=
