sudo: required
language: node_js
node_js:
- '8'
script:
- npm test
deploy:
  provider: npm
  email: spanners@findmypast.com
  api_key:
    secure: r+nE3lRqYyWZR6s+QE+TeoIaSeBBOx9x3tkH37fjsJnNqFIKF7GgT5n8yXkdCg1Z1jEBHxJ1bqgmGjj2imtppdh2glQzcs44pvcEPU9tizf3dKiF7sP0PY/XoIF34tjpgAGmapCzD2D0IIEPnze8SZUEdEXcXWPMOpea9aPFf2/6lTyzdNsu1MwfDGNuS/s0M6LPokJAFWkwGBoI+WbGExF3O/RQ0+c1d53CG0ZAL0Pmc5DThYnYiIlXF/FkByklXzhnTae75OaehpFvOxlXUfY+IEWnrBwuLQE/sDCEXi/UmnRGKh3O5R8X1rrDkPz3prz/6t7JHGhfU7MvIBx7aLTo5iLbW+Uzj3fOEnpAS8UPK8R+L6guy08bzyPAFMBLo8UwUjqF6FdT4+/3qP89hhxlXKylsIu+alNHKiKRn7ftfARPYuarq6K+n3UupR4lQFcid4cit3CV2ggH5LiyXgwP6wBRhNOBYwwRoWG+WOaJcPANef8eKw+X9991T5egIT04MXe8PpoHK1PCQuD5GZv91S8XdK0lJcsTfpslXYnNDHdYjFnDfElgelKoLDE42IjXS8pHU0bZ9Re2yUqF/C8Tv6Qm0zhWuKQAWDBYgOsndo+2j7U4XesqfQZE7hJRbq2TPCKTxk/9G4cRGkqKiCNGapPV3UABZ9FBj+S39N4=
  on:
    tags: true
    repo: findmypast-oss/scoosh
notifications:
  slack:
    secure: n8CNXbGl/wtsacVg9+i/hFOq+zGR7oSIaxPoQb2XhkZOwSSTYw4IPjxsnEAGvXLMeVOHgnD1jEPXw1c5cHpOu3sUW5sDEl9EYXaIWU3EfB6rAQkfgF5eOChXBo+MpVeUkVLy1OCpo4/j5qfnoQb9yxZ4sjVGHrFNLdDpriLU9UQZN8W7IZs6C0jWwqWVXwUa2nXMtBEp1Wm93yQcaehfxF06DHuRaSln5CUBFX2UbVIRgxNDjNbXF9UOmlK5yJlYTXtoOXcelKMo399qzu6YsGVjBQq32nWWKoKWvuK/mqR8kZXMkfOeFvUIbhwkperxYioGOw1Fe/XUzG6BSr6si/7DYda4c5jsQwu6+W/rOTDuF56vBnhl20Es6fEsVT+mVCxopk3OkwfQMg4DZiqKlXhvEyXlzHKMgn0bfDg0PbnFwzIYjcz7jZ8Wt4mhHM2v8AyCHXHeVdftw5uQiXR2jvi7swSUmRNgaLHLC9CF/5+sKJD8AO+Dfdlw+ry7BtixglWs03wNYSFUaluoh23lyxRiK0r8E1pzm/9MJN3egS3iPgOAiMTMl2qk6aGLoDJvinXibI+b+IlEBKirnasrKE8RdW8ufrSjcLJoq2JtXd7DItwdMnasUt8nLl6V67XoOqUrGEbXwvw/NAtFuDD8F5u81d/o80qsTFnFPyGnsis=    
