sudo: required
language: node_js
node_js:
- '8'
script:
- npm test
deploy:
  provider: npm
  email: spanners@findmypast.com
  api_key:
    secure: g+hsKfFwtFh2zuGTE8l/tS9BVk1SOPC9gfAfKPd9qHCQLG7tvVqN2FaHAzRK9zdUFBrBH8HqtiPu37iWEeygt7N1CGtRGGBYCkZsrfoAI00Q55SFDpWMoSqBbpiAjqlIT54z/MgAt3OnwxPJ5CID5rvaUUiMITB2XcSOQ7+BkNE/sPiYvAeZogdCFFFpNr//cT5k5NqeeCPmq282twGhEwroHl4Iv/fJdN+R0EgY9luccpQjgSzmX2fEmJeUz1AghJ9riCq6Z0YIuUo7IoyMvxia9IvSJ4skRxnRLE0dpKpBZIcJhjBCJSi0ior252bm0dJWQCTBIDc7ZcEWZZhQ5QgscQHDC4reUQvU111dyPbp+XyIldUt45Bdyqtp9YgKqC+mGn7HOyJkAlYBDlFRxWCH3lIyAoNsdnytUSaNyDv0A3iTtzEqd69SXjFBlzm4Bf2i14qP/jZq+3XGkJAdzhW/KVf6syzaCKWnc/++mj6rNxXEFDkhngV8fubzkttDvk+4rDg6gFAe+yCKFLELECH0F2btEfFnQDSNLut1TWHLh/4fw414lt1B/2pTsXZRLA8jNzR+wXH9KQqI8AYbbMvPliVrPqDmZAdF3uhK7gKYmKLKzwkAOZwld6wjy57+AGKhHHqkj5RkU3IWIJtWuu59b16ZoccGOGitp1tDtSs=
  on:
    tags: true
    repo: findmypast-oss/scoosh
notifications:
  slack:
    secure: n8CNXbGl/wtsacVg9+i/hFOq+zGR7oSIaxPoQb2XhkZOwSSTYw4IPjxsnEAGvXLMeVOHgnD1jEPXw1c5cHpOu3sUW5sDEl9EYXaIWU3EfB6rAQkfgF5eOChXBo+MpVeUkVLy1OCpo4/j5qfnoQb9yxZ4sjVGHrFNLdDpriLU9UQZN8W7IZs6C0jWwqWVXwUa2nXMtBEp1Wm93yQcaehfxF06DHuRaSln5CUBFX2UbVIRgxNDjNbXF9UOmlK5yJlYTXtoOXcelKMo399qzu6YsGVjBQq32nWWKoKWvuK/mqR8kZXMkfOeFvUIbhwkperxYioGOw1Fe/XUzG6BSr6si/7DYda4c5jsQwu6+W/rOTDuF56vBnhl20Es6fEsVT+mVCxopk3OkwfQMg4DZiqKlXhvEyXlzHKMgn0bfDg0PbnFwzIYjcz7jZ8Wt4mhHM2v8AyCHXHeVdftw5uQiXR2jvi7swSUmRNgaLHLC9CF/5+sKJD8AO+Dfdlw+ry7BtixglWs03wNYSFUaluoh23lyxRiK0r8E1pzm/9MJN3egS3iPgOAiMTMl2qk6aGLoDJvinXibI+b+IlEBKirnasrKE8RdW8ufrSjcLJoq2JtXd7DItwdMnasUt8nLl6V67XoOqUrGEbXwvw/NAtFuDD8F5u81d/o80qsTFnFPyGnsis=
