sudo: required
language: node_js

node_js:
- '8'

script:
- npm test

deploy:
  provider: npm
  email: spanners@findmypast.com
  api_key:
    secure: 2fUrgU/vQnLAX8nJGz4zTKKlApBSAI7aUr8+n9fpePG4pfh6tCCYuF1GdMOHiKUQAs3vFIp2BpVa6PvX9kAf1EokPdUGpXzXPuC/uat4rY9t0Q8NHU5gV+Pk3CNZbczyM8xgI1Dy6BVnT/28eQvsWw2KA+rwVW4Q1vqnOFJqYLcJ4b8zFtMbSgamh2Ab40dekYBZRE69gp6hKrw3zkQVo/xpkstmCDRYzTOEeQbX9cKb5q2q92e7/vbCB3sFLQxW62m35JKGiyEFEN/6iIBwFcWw5Zzze3LRtlFEdob47MEv6Yv2BXnFIyzpV9YZoEOvbhGKFmBbMfyqTZzAHneVag1wOx6qNfV9/AeGgtkr7dIYmwx9UedJ4vEJeDf+wAKkE7+9OYd4WwEXzm/eEZVTTUgH/VEZleURx0vq5ds7Q+l9g9pHy6TVWUHcrCEbgdIEcgfAf7FhR3ztWvPh8zSXHDBHUQHUs1z9z+1237YymLJEkfjVr5C422VW4WYLMJEytrx54EW2POgJLjZfDJK7fA34daH67Jn8F2yjMQdvyOvFKiOrQChLeKzLRS+LT8LO9kvjDxFZhqYEAhzBMXE0u8Rqqan8L7nf71SdofhR2Yj42NYJSuTEa5CkFeTYPSQQ1RQ+XL4kMO3QuJB4J6OZm7Nd8rGsEsMo3VIg5DgNnqI=
  on:
    tags: true
    repo: findmypast-oss/scoosh

notifications:
  slack:
    secure: n8CNXbGl/wtsacVg9+i/hFOq+zGR7oSIaxPoQb2XhkZOwSSTYw4IPjxsnEAGvXLMeVOHgnD1jEPXw1c5cHpOu3sUW5sDEl9EYXaIWU3EfB6rAQkfgF5eOChXBo+MpVeUkVLy1OCpo4/j5qfnoQb9yxZ4sjVGHrFNLdDpriLU9UQZN8W7IZs6C0jWwqWVXwUa2nXMtBEp1Wm93yQcaehfxF06DHuRaSln5CUBFX2UbVIRgxNDjNbXF9UOmlK5yJlYTXtoOXcelKMo399qzu6YsGVjBQq32nWWKoKWvuK/mqR8kZXMkfOeFvUIbhwkperxYioGOw1Fe/XUzG6BSr6si/7DYda4c5jsQwu6+W/rOTDuF56vBnhl20Es6fEsVT+mVCxopk3OkwfQMg4DZiqKlXhvEyXlzHKMgn0bfDg0PbnFwzIYjcz7jZ8Wt4mhHM2v8AyCHXHeVdftw5uQiXR2jvi7swSUmRNgaLHLC9CF/5+sKJD8AO+Dfdlw+ry7BtixglWs03wNYSFUaluoh23lyxRiK0r8E1pzm/9MJN3egS3iPgOAiMTMl2qk6aGLoDJvinXibI+b+IlEBKirnasrKE8RdW8ufrSjcLJoq2JtXd7DItwdMnasUt8nLl6V67XoOqUrGEbXwvw/NAtFuDD8F5u81d/o80qsTFnFPyGnsis=
