sudo: required
language: node_js
node_js:
- '8'
script:
- npm test
deploy:
  provider: npm
  email: spanners@findmypast.com
  api_key:
    secure: WwSSoR6VTCdZflGRrEqu60kemeChY5SwriIUD8cKom4k8yG24HtJkOHwIh6gfS4n2KUadOKYmT4BsWQ6WfJMZ1MeUDeUJtI9ZkCk3FQ7rsuz9NHi2yfJmhk5nYoPWLmHubrqFi55Iwsgllc/Hw8cldUcW8NXu38bpI+2pOcavYTUxc4yqEcPhELxR0IbJFlE/M/iBNSy+6ymNZAql3iLyfnf3AfchlujgYZQ25ZW7UPuGO8hrJnVofyHR9i2gRZkbyIz1xVodf3dF8pP/Nkv6Qs0ZWPb2OQ1pQFLZIyKhzXt8f47hfKux3I2IWKy9w+Witx58QAKskNH1Bye2XsA6TuN0kmld9tn6DCHcr9A2VRopoviDqUDiA+i0qioHtTAapUMXIxhHv2+HK/MihsZxmYctFg1yyttBEb7XNuhgjyz+rDG6ZugUEzM+uQjKahu+7i+6R26SIVrLGHPWd/0//mrRvmaX7eN3dSURYX0MxlWCFiOwham2u83mYwf2//YZNuPi35yFFdngaKY1VuYUGdZqWFa1P6vPiZJiWef4YcnfnU6wbDEiF8qbi1m+nkDreVWEwDp+gPcuMhG5CynWyf9YGTO5b9SedGsy0EtXYrEwAe/0l1ChlTWfWE35wjJ6Cgd+8BhyfhYC1LtbzViW7lYElon/1U+K9Vh+FKq3W8=
  on:
    tags: true
    repo: findmypast-oss/scoosh
notifications:
  slack:
    secure: n8CNXbGl/wtsacVg9+i/hFOq+zGR7oSIaxPoQb2XhkZOwSSTYw4IPjxsnEAGvXLMeVOHgnD1jEPXw1c5cHpOu3sUW5sDEl9EYXaIWU3EfB6rAQkfgF5eOChXBo+MpVeUkVLy1OCpo4/j5qfnoQb9yxZ4sjVGHrFNLdDpriLU9UQZN8W7IZs6C0jWwqWVXwUa2nXMtBEp1Wm93yQcaehfxF06DHuRaSln5CUBFX2UbVIRgxNDjNbXF9UOmlK5yJlYTXtoOXcelKMo399qzu6YsGVjBQq32nWWKoKWvuK/mqR8kZXMkfOeFvUIbhwkperxYioGOw1Fe/XUzG6BSr6si/7DYda4c5jsQwu6+W/rOTDuF56vBnhl20Es6fEsVT+mVCxopk3OkwfQMg4DZiqKlXhvEyXlzHKMgn0bfDg0PbnFwzIYjcz7jZ8Wt4mhHM2v8AyCHXHeVdftw5uQiXR2jvi7swSUmRNgaLHLC9CF/5+sKJD8AO+Dfdlw+ry7BtixglWs03wNYSFUaluoh23lyxRiK0r8E1pzm/9MJN3egS3iPgOAiMTMl2qk6aGLoDJvinXibI+b+IlEBKirnasrKE8RdW8ufrSjcLJoq2JtXd7DItwdMnasUt8nLl6V67XoOqUrGEbXwvw/NAtFuDD8F5u81d/o80qsTFnFPyGnsis=
